### ISSUE TITLE
Has iOS5 support been removed from the pod?

### ISSUE THREAD

**Issue by tatejones** [nicolaschengdev/WYPopoverController#30]
Performing a pod update generates the following error.

[!] The platform of the target `Pods` (iOS 5.1) is not compatible with `WYPopoverController (0.1.4)` which has a minimum requirement of iOS 6.0.

**Comment by tatejones** [comment]
Missing?

 s.platform     = :ios, '5.1'

**Comment by nicolaschengdev** [comment]
Hi tatejones,

no it's not missing.

Because I decided to remove support of iOS 5.1 for `WYPopoverController`.

For now with [0.1.4] release, I have only tested with SIMULATOR. It seems to work.

The solution, in your PodFile, write : 

``` Ruby
platform :ios, '6.0'
pod 'WYPopoverController', '~> 0.1.4'
```

And configure _deployment target_ of your project to iOS 5.1 .

**Nicolas**
