### ISSUE TITLE
Add support for keyboard show/hide

### ISSUE THREAD

**Issue by nicolaschengdev** [nicolaschengdev/WYPopoverController#7]
If the keyboard is shown or hidden then popover should adjust this layout.

**Comment by edward-lay** [comment]
Is this still in progress because I do have bug.

I have textfield that is inside the Popover Controller and when keyboard is shown, the popover is covered by the iPad keyboard. 

For my other textfield in the app, I have TPKeyboardAvoiding to help me adjust the view.

**Comment by nicolaschengdev** [comment]
I have just tested this functionality under iOS7.
It works but a serious performance issue appears.
Please consider this functionality is still in progress.
Sorry for the inconvenience.

**Comment by priore** [comment]
When keyboard is shown, the popover is covered by the iPhone (ios7) keyboard.

**Comment by edward-lay** [comment]
I have illustrated my example in sketches, pardon my drawing (=

http://sketchtoy.com/56683196

There are 3 scenarios, and the sketches tells the estimated position of the buttons/popover/keyboard. So for the first scenario: the popover auto-shifted which was the normal behaviour. I believe this was because the popover detects that it has sufficient space above it and thus it could adjust and re-position.

2nd scenario: The popover didn't re-position itself. I was thinking if are there any methods to reposition itself to the right so part of it will not be covered by keyboard?

3rd scenario: The popover didn't re-position itself too. 

The codes used are similar. Could you look into this? I really like how much customisation this framework can offer me and your active support. Thanks in advance.

**Comment by nicolaschengdev** [comment]
I understood your drawings and I shall take a look as soon as possible. Unfortunately I am very busy with my others projects. So please be patient ! ^^

**Comment by edward-lay** [comment]
Just found out that the issues are with WYPopoverArrowDirectionDown and WYPopoverArrowDirectionUp, WYPopoverArrowDirectionLeft and WYPopoverArrowDirectionRight does shift itself when the keyboard appears

**Comment by edward-lay** [comment]
IT WORKS!!!! (= 

thanks Nicolas!
