### ISSUE TITLE
UIImagePickerController on iPad

### ISSUE THREAD

**Issue by thepaddedcell** [nicolaschengdev/WYPopoverController#9]
Is it possible to use UIImagePickerController with WYPopoverController on iPad?

When I tried to do so, I received the following error:

`On iPad, UIImagePickerController must be presented via UIPopoverController`

**Comment by nicolaschengdev** [comment]
Hi !

The documentation indicates that on iPad :

> If you specify a source type of _UIImagePickerControllerSourceTypePhotoLibrary_ or 
> _UIImagePickerControllerSourceTypeSavedPhotosAlbum_, you must present the image picker using a popover 
> controller ( _UIPopoverController_ ). If you attempt to present an image picker modally (full-screen) for choosing 
> among saved pictures and movies, the system raises an **exception**.
> 
> If you specify a source type of _UIImagePickerControllerSourceTypeCamera_, you can present the image picker 
> modally (full-screen) or by using a popover. However, Apple recommends that you present the camera interface 
> only full-screen.

No, it's not possible to use your image picker ( _UIImagePickerController_ ) without _UIPopoverController_ on iPad if your picker is for choosing saved pictures and movies.

However, it's possible to use something else that an _UIImagePickerController_.

Few links :

[AGImagePickerController](https://github.com/arturgrigor/AGImagePickerController)
[CZPhotoPickerController](https://github.com/carezone/CZPhotoPickerController)
[PhotoPickerPlus](https://github.com/chute/photo-picker-plus/tree/master/iOS/PhotoPickerPlus)

**Comment by thepaddedcell** [comment]
Thanks Nicolas. I was hoping you knew a trick or something to get around this :)

Any recommendation of the 3 links you provided, if I decide to head down that route?

**Comment by nicolaschengdev** [comment]
I cannot give you a recommendation on links because I didn't try one of them.
Ask yourself if your app is only for iPad and/or you need, for example, multiple selection for your picker.

My thought is :
If your app is only for iPad and you just need the standard features of `UIImagePickerController` class then you have to consider to only subclass the `UIPopoverBackgroundView` class based on images. Because the amount of works is lower in this case. 

Nicolas
